#pragma once

#include <Arduino.h>

// Piezo buzzer driven push-pull across two GPIOs (BUZZ1/BUZZ2). Driving the
// pins in antiphase — one HIGH while the other is LOW, swapped each half cycle
// — doubles the voltage swing across the element versus driving one pin against
// a fixed reference, which is the whole point of the two-GPIO wiring.
//
// The element is a 4 kHz resonant type; it is loudest driven at its resonant
// frequency (see BUZZER_RESONANT_HZ). Tones are generated by blocking bit-bang,
// which is plenty for bring-up and simple production beeps.
class Buzzer {
  public:
    static constexpr uint32_t RESONANT_HZ = 4000; // element's loudest frequency

    // Configure both pins as outputs, idle LOW (silent).
    void begin(uint8_t pinA, uint8_t pinB);

    // Blocking antiphase square wave at freqHz for durationMs, then silent.
    void tone(uint32_t freqHz, uint32_t durationMs);

    // Blocking glissando: linearly slides from fromHz to toHz over durationMs.
    // Rising sweeps read as "happy/on", falling as "sad/off" — much more
    // expressive on a piezo than fixed-pitch beeps.
    void sweep(uint32_t fromHz, uint32_t toHz, uint32_t durationMs);

    // Convenience: a beep at the element's resonant frequency.
    void beep(uint32_t durationMs) { tone(RESONANT_HZ, durationMs); }

    // Force both pins LOW (no DC across the element).
    void off();

  private:
    uint8_t pinA_ = 0xFF;
    uint8_t pinB_ = 0xFF;
};
